version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-xray-stack-4"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w2czswtyx93l"
s3_prefix = "lambda-xray-stack-4"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
